name: llama-omni2
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.14
  - aom=3.9.1
  - attr=2.5.1
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - dav1d=1.2.1
  - dbus=1.16.2
  - expat=2.7.1
  - ffmpeg=7.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gmp=6.3.0
  - graphite2=1.3.14
  - harfbuzz=11.3.3
  - icu=75.1
  - lame=3.100
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - level-zero=1.24.1
  - libabseil=20250512.1
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.4
  - libcap=2.75
  - libdeflate=1.24
  - libdrm=2.4.125
  - libegl=1.7.0
  - libexpat=2.7.1
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgl=1.7.0
  - libglib=2.84.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenvino=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-intel-cpu-plugin=2025.2.0
  - libopenvino-intel-gpu-plugin=2025.2.0
  - libopenvino-intel-npu-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.7
  - libtiff=4.7.0
  - libudev1=257.7
  - libunwind=1.8.2
  - liburing=2.11
  - libusb=1.0.29
  - libuuid=2.38.1
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - mpg123=1.32.9
  - ncurses=6.5
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.6.0
  - openssl=3.5.2
  - pango=1.56.4
  - pcre2=10.45
  - pip=25.1
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pugixml=1.15
  - pulseaudio-client=17.0
  - python=3.10.18
  - readline=8.3
  - sdl2=2.32.54
  - sdl3=3.2.20
  - setuptools=78.1.1
  - snappy=1.2.2
  - sqlite=3.50.4
  - svt-av1=3.0.2
  - tbb=2022.2.0
  - tk=8.6.13
  - wayland=1.24.0
  - wayland-protocols=1.45
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcursor=1.2.3
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==0.33.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - beautifulsoup4==4.13.4
      - bitsandbytes==0.45.0
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - click==8.2.1
      - coloredlogs==15.0.1
      - conformer==0.3.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.1.2
      - datasets==2.18.0
      - decorator==5.2.1
      - diffusers==0.27.2
      - dill==0.3.8
      - einops==0.6.1
      - einops-exts==0.0.4
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - fastapi==0.115.11
      - ffmpy==0.6.1
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2024.2.0
      - gdown==5.1.0
      - gradio==5.3.0
      - gradio-client==1.4.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.25.1
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - hyperpyyaml==1.2.2
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - inflect==7.3.1
      - jinja2==3.1.6
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - latex2mathml==3.78.0
      - lazy-loader==0.4
      - librosa==0.10.2
      - lightning==2.2.4
      - lightning-utilities==0.15.2
      - llama-omni2==1.0.0
      - llvmlite==0.44.0
      - markdown-it-py==3.0.0
      - markdown2==2.5.2
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.3
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - onnx==1.16.0
      - onnxruntime-gpu==1.18.0
      - openai-whisper==20231117
      - openpyxl==3.1.5
      - orjson==3.11.1
      - packaging==24.2
      - pandas==2.3.1
      - peft==0.14.0
      - pillow==10.4.0
      - platformdirs==4.3.8
      - pooch==1.8.2
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pyarrow-hotfix==0.7
      - pycparser==2.22
      - pydantic==2.7.0
      - pydantic-core==2.18.1
      - pydub==0.25.1
      - pygments==2.19.2
      - pynini==2.1.5
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.3
      - rich==14.1.0
      - ruamel-yaml==0.18.14
      - ruamel-yaml-clib==0.2.12
      - ruff==0.12.8
      - safetensors==0.6.2
      - scikit-learn==1.2.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.7
      - soxr==0.5.0.post1
      - starlette==0.46.2
      - svgwrite==1.4.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tiktoken==0.11.0
      - timm==0.6.13
      - tokenizers==0.19.1
      - tomlkit==0.12.0
      - torch==2.3.1
      - torchaudio==2.3.1
      - torchmetrics==1.8.1
      - torchvision==0.18.1
      - tqdm==4.67.1
      - transformers==4.43.4
      - triton==2.3.1
      - typeguard==4.4.4
      - typer==0.16.0
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.30.0
      - wavedrom==2.0.3.post3
      - websockets==12.0
      - wetextprocessing==1.0.3
      - wget==3.2
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
